== Exercise: Implementing a data backup of application settings
	
=== Project implementation
		
The following application uses the
`com.vogella.android.databackup`
top level package. This package was registered with the Google
service.
		
The backup agenda and the registration key is entered in the
_AndroidManifest.xml_
file as in the following listing.
		
[source,java]
----
include::res/backup/AndroidManifest.xml[]
----
		
The corresponding backup agent can be implemented as
demonstrated
in the following listing.
		
[source,java]
----
include::res/backup/MyBackupAgent.java[]
----		
	
=== Trigger backup and restore

The implemented backup manager works automatically without user
interaction and saves and restores the registered shared preferences
associated with the user.
Simply change and save shared preferences
under the file name which
you registered your application with.
		
If you want to test the save and restore operation via the adb
shell command you can use the following commands.
		
[source,java]
----
include::res/backup/backuptest.txt[]
----		
	
