== Automatically starting Services from a Receivers

A common requirement is to automatically start a service after a
system reboot, i.e., for synchronizing
data. For this you can register
a receiver
for the
`android.intent.action.BOOT_COMPLETED`
system event. This requires the
`android.permission.RECEIVE_BOOT_COMPLETED`
permission.

The following example demonstrates the registration for the
`BOOT_COMPLETED`
event in the Android manifest file.

[source,xml]
----
include::res/autostart/AndroidManifest.xml[]
----

The receive would start the service as demonstrated in the
following example code.

[source,java]
----
include::res/autostart/start.java[]
----

TIP: If your application is installed on the SD card, then it is not
available after the
`android.intent.action.BOOT_COMPLETED`
event. In this case register it for the
`android.intent.action.ACTION_EXTERNAL_APPLICATIONS_AVAILABLE
`
event.

NOTE: Remember that as of Android API level 11 the user needs to have
started
the
application at least once before your application can
receive
`android.intent.action.BOOT_COMPLETED`
events.

