== Accessing SQLite databases directly

=== Storage location of the SQLite database

SQlite stores the whole database in a file. If you have access
to this file, you can work directly with the data base. Accessing the
SQlite database file only
works in the
emulator or on a rooted
device.
		
A
standard Android device
will not
grant read-access to the
database file.
		
=== Shell access to the database
		
It is possible to access an SQLite database on the emulator or a
rooted device via the command line. For this use the following
command
to
connect to the device.
		
[source,java]
----
include::res/commandline/shell.txt[]
----		

The command adb is located in your Android SDK installation
folder in the "platform-tools" subfolder.
		

Afterwards you use the "cd" command to switch the database
directory and use the "sqlite3" command to connect to a
database. For
example in my case:
		
[source,java]
----
include::res/commandline/shell1.txt[]
----		
		
The most important commands are:

.SQlite commands
|===
|Command |Description

|.help
|List all commands and options.

|.exit
|Exit the sqlite3 command.

|.schema
|Show the CREATE statements which were used to create the tables of the current database.
|===
	
You find the complete documentation of SQlite at
http://www.sqlite.org/sqlite.html[http://www.sqlite.org/sqlite.html].
	
