== Programming tips for providing highly responsive and fast Android applications

=== Why you should be careful with Android resources

Android devices have less power than standard desktop or notebook computers. 
For this reason you must be careful with memory consumption.

Especially on Android devices before Android 5.0 you want to avoid triggering the garbage collector of the
Java virtual machine. 
This results in a freeze of the Android runtime for about 200 ms.
This can be a notable delay, if the user is, for example, scrolling down a list.

=== Avoid unnecessary object allocation
	
Avoid creating unnecessary objects, especially in expensive places. 
Reuse objects if possible.
Creating unnecessary objects triggers the garbage collection more frequently, and this should be avoided.

For example avoid object creating in loops or in the `onDraw()` method of your custom view.
	
=== Use efficient data structures
	
Android provides several implementations of `Sparse*Array`
classes. Consider the following code.
	
[source,java]
----
include::res/memory/createHashMap.java[]
----
	
Using this code results in unnecessary `Integer` objects created.

Android provides data structures which are more efficient for mapping values to other objects. 
If possible use these objects, they avoid object creation as in the case of using HashMap. 
Object creation can be expensive and should be avoided to reduce the number of times the garbage collector needs to run.
	
The table give examples for SparseArrays.

.Efficient memory structures
|===
|Memory structure |Description

|<![CDATA[SparseArray<E>]]>
|Maps integers to Objects, avoid the creation of Integer objects.

|SparseBooleanArray
|Maps integers to booleans. 

|SparseIntArray
|Maps integers to integers
|===
	
To improve the above example, prefer to use the following data structure.
	
[source,java]
----
include::res/memory/createSparseArray.java[]
----

