== Android library projects and Java libraries

=== Using Java and Android libraries

Android project can use code contained in _JAR_ files (Java libraries). 

In addition to JAR files, the Android uses a binary distribution format called _Android ARchive(AAR)_. 
The _.aar_ bundle is the binary distribution of an Android Library Project.
	
An AAR is similar to a JAR file, but it can contain resources as well as compiled byte-code. 
A AAR file can be included in the build process of an Android application similar to a _JAR_ file.
	


It is possible to create libraries modules which can be used as dependencies in Android projects.
These modules allow you to store source code and Android resources which can be shared between several other Android projects.
	

=== How to use a standard Java library (JAR) file in your Android application
		
To use a Java library (JAR file) inside your Android project, you can simple copy the _JAR_ file into the folder called _libs_ in your application. 
*.jar files in this folder are included into the compile classpath via the default build.gradle file.
		
=== Restrictions in using Java libraries
		
If you want to use libraries, these must only use API available in Android. 
For example, the Android libraries do not contain the `java.awt` and `javax.swing` user interface libraries.
A library which uses classes from these packages cannot be used in Android.
		
Library projects cannot be compiled to Android applications and started without another project using them.
		


	