== Android library project
	
The Android team introduced a new binary distribution format
called
_Android ARchive(AAR)_
. The
_.aar_
bundle is the binary distribution of an Android Library
Project.
	
An AAR
is similar to a JAR file, but it can contain resources
as
well
as
compiled byte-code. This allows that an AAR
file is
included
in the build
process of an Android application similar to
a
_JAR_
file
	
WARNING: This AAR format is currently directly support by the Eclipse IDE.
Stare on the following issue so that Google solves this issue:
https://code.google.com/p/android/issues/detail?id=59183 Allows Eclipse ADT plugin to work with .AAR files.

TIP: It is still possible to use AAR files with Eclipse. 
You can either convert them to Android library projects as described in
http://commonsware.com/blog/2014/07/03/consuming-aars-eclipse.html - Consuming AARs from Eclipse blog post about it.
Or use the
https://code.google.com/p/maven-android-plugin/wiki/AAR - Android Maven plug-in for your build.

