=== Create log statements
(((BuildConfig)))
    
To write log statements, you use the
`android.util.Log`
class with the
`Log.v()`
,
`Log.d()`
,
`Log.i()`
,
`Log.w()`
,
`Log.e()`
or
`Log.wtf()`
method. They are sorted by relevance with
`Log.i()`
being the least important one.
The first
parameter of these methods is the category
and
the second
is the
message.
    

    
Typically you create a
`Constants`
interface in your Android application and provide your log flag as a
field.
    
   
[source,java]
---- 
include::res/log/Constants.java[]
----  
    
Android advises that a deployed application should not contain
logging
code. The Android development tools provide the
`BuildConfig.DEBUG`
flag for this purpose. This flag will be automatically set to
`false`
if you export the Android application for deployment. During
development it will be set to
`true`
, therefore allowing you to see your
logging statements during
development.
    
    
The following example show how to write an error log message.

[source,java]
----
include::res/log/log.java[]
----

