== Application
	
The application object is created whenever one of your Android
components are started. It is started in a new process with a unique
ID under a unique user. Even if you do not specify one in your
_AndroidManifest.xml_
file, the Android system creates a default object for you.
This object
provides the following main lifecycle methods:

* onCreate() - called before the first components of the application starts
* onLowMemory() - called when the Android system requests that the application cleans up memory
* onTrimMemory() - called when the Android system requests that the application cleans up memory. 
This message includes an indicator in which position the application is. 
For example the constant TRIM_MEMORY_MODERATE indicates that the process is around the middle of the background LRU list; freeing memory can help the system keep other processes running later in the list for better overall performance.
* onTerminate() - only for testing, not called in production
* onConfigurationChanged() - called whenever the configuration changes

The application object starts before any component and runs at least as long as another component of the application runs.

