== Android File API

=== Using the file API

Access to the file system is performed via the standard
`java.io`
classes.
Android provides also helper classes for creating and
accessing new
files and directories.
For example the
`getDir(String, int)`
method
would create or
access a directory. The
`openFileInput(String s)`
method
would
open
a file for input
and
`openFileOutput(String s, Context.MODE_PRIVATE)`
would
create a
file.

Android supports world readable or writable files, but it is
considered good practice to keep files private to the application and
use content provider if you want to share data with other
applications.

The following example shows the API usage.

[source,txt]
----
include::res/snippets/fileapiwrite.txt[]
----

[source,txt]
----
include::res/snippets/fileapiread.txt[]
----
	
=== External storage

Android supports also access to an external storage system e.g.
the SD card. All files and
directories on the external storage system
are readable for all
applications with the correct permission.

To read from external storage your application need to have the
`android.permission.READ_EXTERNAL_STORAGE`
permission.

To
write to
the external storage system your application needs the
`android.permission.WRITE_EXTERNAL_STORAGE`
permission. You get the path to the
external storage system via the
`Environment.getExternalStorageDirectory()`
method.

Via the following method call you can
check the state of the
external storage system. If the Android
device is
connected via USB to
a computer, a
SD
card which might be used for the external storage
system is
not
available.

[source,txt]
----
include::res/snippets/sdavailable.txt[]
----

The following shows an example for reading from the external
storage system.

[source,txt]
----
include::res/snippets/sdcard.txt[]
----

