== Parts of an Android application

[[androidapplication]]
=== Android application
		
An _Android application_ is a single installable unit which can be started and used independently of other Android applications.
		
		
An Android application consists of Android components, Java source and resource files.
		
		
Android application components can connect to components of other Android applications based on a task description represented by an `Intent` object.
This way they can create cross-application tasks. 

[[androidcomponents_overview]]		
=== Android software components
		
The following Android components can be defined:
* Application object
* Activities
* Services
* Broadcast receivers (short: receivers)
* Content providers (short: providers)
		
[[components_application]]
=== Application
		
An Android application can have one `Application` class which is instantiated before any other Android component.
Tt is the last component which is stopped during application shutdown.
		
If not explicitly defined, Android creates a default application object for your application.

[[components_activity]]
=== Activity
		
An _activity_ is the visual representation of an Android application.
An Android application can have several activities.
		
		
Activities use views and fragments to create their user interface and to interact with the user. 
Both elements are described in the next sections.

[[components_broadcastreceiver]]
=== BroadcastReceiver
		
A _broadcast receiver_ (receiver) can be registered to listen to system messages and intents. 
A receiver gets notified by the Android system if the specified event occurs.
		
For example, you can register a receiver for the event that the Android system finished the boot process. 
Or you can register for the event that the state of the phone changes, e.g., someone is calling.

[[components_services]]
=== Service
		
A _service_ performs tasks without providing an user interface.
They can communicate with other Android components. 
For example, a broadcast receiver can notify the user via the notification framework in Android.


[[components_contentprovider]]
=== ContentProvider
		
A _content provider_ (provider) defines a structured interface to application data. 
A provider can be used for accessing data within one application, but can also be used to share data with other applications.
		
Android contains an SQLite database which is frequently used in conjunction with a content provider. 
The SQLite database would store the data, which would be accessed via the provider.

[[overview_context]]
=== Context
		
Instances of the class `android.content.Context` provide the connection to the Android system and device the application is running on.
It gives access to the system and application resources and services
		
For example, you can check the size of the current device display via the `Context`.
		
Activities and services extend the `Context` class. 
Therefore, they can be directly used to access the `Context`.
		
