== Using and accessing static resources

=== References to resources in code
		
The `Resources` class allows to access individual resources. 
An instance of the `Resources` class can be retrieved via the `getResources()` method of the `Context` class. 
As activities and services extend the `Context` class, you can directly use this method in implementations of these components.


An instance of the `Resources` class is also required by other Android framework classes. 
For example, the following code shows how to create a `Bitmap` file from a reference ID.

[source,java]
----
include::res/resources/LoadBitmap.java[]
----
		
=== Accessing views from the layout in an activity
		
In your activity (and fragment) code you frequently need to access the views to access and modify their properties.

		
In an activity you can use the `findViewById(id)` method call to search for a view in the current layout. 
The `id` is the ID attribute of the view in the layout. 
The usage of this method is demonstrated by the following code.
		
		
[source,java]
----
@Override
protected void onCreate(Bundle savedInstanceState) {
	super.onCreate(savedInstanceState);
	setContentView(R.layout.activity_main);
	TextView textView = (TextView) findViewById(R.id.mytext);
        
    // TODO do something with the TextView
}
----
		
It is also possible to search in a view hierarchy with the `findViewById(id)` method, as demonstrated in the following code snippet.

[source,java]
----
// search in the layout of the activity
LinearLayout linearLayout = (LinearLayout) findViewById(R.id.mylayout);

// afterwards search in linearLayout for another view
TextView textView = (TextView) linearLayout.findViewById(R.id.mytext);

// note, you could have directly searched for R.id.mytext, the above coding
// is just for demonstration purposes
----


[TIP]
====
You could also build a utility method which makes access to views easier.

[source,java]
----
package com.example.android.test;

import android.app.Activity;
import android.view.View;

public class UiUtils {
   public static <T extends View> T findView(View root, int id)      {
      return (T) root.findViewById(id); }

   public static <T extends View> T findView(Activity activity, int id)      {
      return (T) activity.getWindow().getDecorView().getRootView().findViewById(id); }
}
----

This would allow you to find the view without explicit cast in your view hierarchy.

[source,java]
----
Button button = UiUtils.findView(this, R.id.button);
----
====
		
=== Reference to resources in XML files
		
In your XML files, for example, your layout files, you can refer to other resources via the `@` sign.
		
		
For example, if you want to refer to a color, which is defined in an XML resource, you can refer to it via `@color/your_id`.
Or if you defined a `String` with the `"titlepage"` key in an XML resource, you could access it via `@string/titlepage`
		
To use an Android system resource, include the `android` namespace into the references, e.g., `android.R.string.cancel`.
		
=== Using assets?
		
The _res_ directory contains structured values which predefined semantics for the Android platform.
The _assets_ directory can be used to store any kind of data.
You can access files stored in this folder based on their path. 
The _assets_ directory also allows you to have sub-folders.

[NOTE]
====
You could also store unstructured data in the _/res/raw_ folder. 
But it is considered good practice to use the _assets_ directory for such data.
====	
		
You access this data via the `AssetsManager` which you can access via the `getAssets()` method from an instance of the `Context` class.
		
The `AssetsManager` class allows you to read a file in the _assets_ folder as `InputStream` with the `open()` method. 
The following code shows an example for this.
		
[source,java]
----
include::res/assets/assets.java[]
----
		

		