== Overview of HTTP access on Android

=== Available official API's

Android contains the standard Java network
`java.net`
package which can be used to access network resources. The base class
for HTTP network access in the
`java.net`
package is the
`HttpURLConnection`
class.

TIP: Android
also
contains the
Apache HttpClient library but it is not
recommended anymore to use it, as Google is focusing their efforts
on improving the
`HttpURLConnection`
implementation.

=== Required permissions

To access the Internet your
application requires the
`android.permission.INTERNET`
permission.

To check the network state your application requires the
`android.permission.ACCESS_NETWORK_STATE`
permission.

=== Open source libraries

Performing network operations on Android can be cumbersome. You
have to open and close a connections, enable caches and ensure to
perform the network operation in a background thread.

To simplify these operations several popular Open Source libraries
are available. The most popular ones are the following:

* Volley
* OkHttp

