== Android Location API

=== Determine the current geolocation

Most Android devices allow to determine the current geo location.
This can be done via a GPS (Global Positioning System) module, via cell tower triangulation and via wifi networks.

Google Play provides the _fused location provider_ to retrieve the device's last known location. 

=== Installation

To use the location manager make the Google play service available via your app build.gradle file.

[source,gradle]
----
dependencies {
	compile 'com.google.android.gms:play-services:9.2.0'
	compile 'com.google.android.gms:play-services-location:9.2.0'
    }
----

Also specify the following required permission in your manifest.


[source,xml]
----
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
----

=== Using the LocationManager

Now you can access the last known location. 
The fuse location provider provides a new simple API.
The following is an example activity which uses it.



=== Forward and reverse Geocoding

The
`Geocoder`
class allows to determine the geo-coordinates
(longitude, laditude)
for a given address and possible addresses for
given geo-coordinates.

This process is known as forward and reverse
geocoding. The
`Geocoder`
class uses an online Google service.

=== Security

If you want to access the GPS sensor, you need the
`ACCESS_FINE_LOCATION`
permission. Otherwise you need the
`ACCESS_COARSE_LOCATION`
permission.

=== Prompt the user to Enabled GPS
The user can decide if the GPS is enabled or not. 

You can find out, if a LocationManager is enabled via the
`isProviderEnabled()`
method. If its not enabled you can send the user to the settings via
an
`Intent`
with the
`Settings.ACTION_LOCATION_SOURCE_SETTINGS`
action for the
`android.provider.Settings`
class.

[source,java]
----
include::res/snippets/checknetwork.java[]
----

Typically you would open an
`AlarmDialog`
prompt the user
and if he wants to enable GPS or if the application
should be canceled.

You cannot enable the GPS directly in your code, the user has to
do this.

