== Exercise: Dynamic replacement of fragments depending on the configuration

=== Target of this exercise
		
In this exercise you use the `FragmentManager` to dynamically add fragments to your activity.
		
		
After you implement this exercise you end up with only one activity and you can delete the `DetailsActivity` at the end of this exercise.
		
=== Use placeholder for the layout files
		
Replace the static fragments in the layout folders with `FrameLayouts` as placeholder. 
The following listing is the entry for the _res/layout_ folder. 
In this layout the second container is defined to be unused (gone).
		
<programlisting language="java">
	<xi:include xmlns:xi="http://www.w3.org/2001/XInclude"
		parse="text" href="./examples/fragmentsdynamic/activity_rssfeed.xml" />
</programlisting>
		

		
The following listing is the entry for the _res/layout-land_ folder.
		
<programlisting language="java">
	<xi:include xmlns:xi="http://www.w3.org/2001/XInclude"
		parse="text" href="./examples/fragmentsdynamic/activity_rssfeedland.xml" />
</programlisting>
		

=== Define a variable to determine if you are in single or dual pane mode
				
Create the following _res/values/config.xml_ configuration file.
		
<programlisting language="java">
	<xi:include xmlns:xi="http://www.w3.org/2001/XInclude"
		parse="text" href="./examples/mode/config.xml" />
</programlisting>
		
		
In the _res/values-land_ folder place the _config.xml_ configuration file with a different value.
		
<programlisting language="java">
	<xi:include xmlns:xi="http://www.w3.org/2001/XInclude"
		parse="text" href="./examples/mode/config2.xml" />
</programlisting>
		

=== Use fragment manager to replace fragments
		
Implement a solution so that you have only one _activity_ which handles the fragments on demand.
		
		
<programlisting language="java">
	<xi:include xmlns:xi="http://www.w3.org/2001/XInclude"
		parse="text" href="./examples/fragmentsdynamic/" />
</programlisting>
