== Support annotations

Google provides a new annotations package.
This package  includes a number of metadata annotations, which you can use in your code, to prevent bugs. 

To use these annotations add the following dependency to your Gradle build file.

[source]
----
dependencies {
    compile 'com.android.support:support-annotations:22.2.0'
}
----

The following information describes the most important annotations. 
See http://tools.android.com/tech-docs/support-annotations for more information.

=== Nullness Annotations

The @Nullable annotation can be used to indicate that a given parameter or return value can be null. 
Similarly, the @NonNull annotation can be used to indicate that a given parameter (or return value) can not be null.

=== Threading Annotations: @UiThread, @WorkerThread, ...

If a method can only be called from a specific type of thread, you can annotate it with one of the following annotations:

* @UiThread
* @MainThread
* @WorkerThread
* @BinderThread

Example:

[source]
----
@WorkerThread
protected abstract Result doInBackground(Params... params);

@MainThread
  protected void onProgressUpdate(Progress... values) {
  }
----


