== Exercise: Use data binding
=== Target of this exercise
		
In this exercise you learn how to interact between your user interface widgets using data binding.
You continue to use the application you created already in <<androidstudio_starter>>.
		
=== Activate the usage of data binding
		
Open your _app/build.gradle_ file and activate the usage of databinding. 
Ensure you pick the correct build file, it is the one with the `application` node in it.

[source,java]
----
include::res/exercise_layoutbutton/build.gradle[]
----
		

=== Create classes for the view interaction

Create the following classes.

[source,java]
----
include::res/exercise_layoutbutton/TemperatureData.java[]
----

[source,java]
----
include::res/exercise_layoutbutton/MainActivityContract.java[]
----

[source,java]
----
include::res/exercise_layoutbutton/MainActivityPresenter.java[]
----


=== Adjust layout files to use data binding
		
Change the layout to the following.
		
[source,xml]
----
include::res/exercise_layoutbutton/activity_main.xml[]
----
		
[NOTE]
====
You see some warning messages in the editor, e.g., because you used hard-codes strings.
We demonstrates later how to get rid of these warning messages.
====

[source,java]
----
include::res/exercise_layoutbutton/solution_MainActivity.java[]
----	
Adjust your `MainActivity` code to activate data binding.
		

=== Validate your application
You can start your application in the emulator or use the layout review in your IDE. 
If you press the button, a small popup should be shown.
