== Handler

=== Purpose of the Handler class

A `Handler` object registers itself with the thread in which it is created.
It provides a  channel to send data to this thread.
For example, if you create a new `Handler` instance in the `onCreate()` method of your _activity_, it can  be used to post data to the main thread.
The data which can be posted via the `Handler` class can be an instance of the `Message` or the `Runnable` class.
A Handler is particular useful if you have want to post multiple times data to the main thread.

=== Creating and reusing instances of Handlers
		
To implement a handler subclass it and override the `handleMessage()` method to process messages.
You can post messages to it via the `sendMessage(Message)` or via the `sendEmptyMessage()` method.
Use the `post()` method to send a `Runnable` to it.
		
To avoid object creation, you can also reuse the existing `Handler` object of your activity.
		
[source,java]
----
include::res/handler/getActivityHandler.java[]
----
		
The `View` class allows you to post objects of type `Runnable` via the `post()` method.
		
=== Example
		
The following code demonstrates the usage of an handler from a  view.
Assume your activity uses the following layout.		
		
[source,xml]
----
include::res/handler/main.xml[]
----
		
With the following code the `ProgressBar` get updated once the users presses the `Button`.
		
[source,java]
----
include::res/handler/ProgressTestActivity.java[]
----
		
	