[[dagger2]]
== Dependency injection with Dagger 2

	<section id="dagger2_overview">
		<title>What is Dagger 2?

		<indexterm>
			<primary>Dependency injection</primary>
			<secondary>Dagger 2</secondary>
		</indexterm>
		<indexterm>
			<primary>Dagger</primary>
		</indexterm>
		
			Dagger 2 is dependency injection framework which uses code generation to create the code necessary for
			dependency
			injection. This code is similar to hand written code.
		
	</section>
	<section id="dagger2_overview_injections">
		<title>Expressing dependencies in Dagger 2
		
			Dagger 2 is based on JSR 330.
			It uses the
			`@Inject`
			annotation
			to express a dependency (a constructor, a field, or a method).
		
		If you use Dagger for dependencies injection for field injection your fields are not allowed to be private, as
			Dagger 2 uses generated code to access the fields and not reflection.
		
	</section>
	<section id="dagger2_overviewdi">
		<title>Defining the dependency injection context
		
			The term
			_dependency injection context_
			is typically used to describe the set of objects which can be injected.
			In Dagger class annotated with
			`@Module`
			are responsible for that.
		

		
			Such classes can define methods annotated with
			`@Provides`
			which can return created objects. A model can provide several dependencies, i.e., methods annotated with
			`@Provides`
			.
		
		
			Methods annotated with
			`@Provides`
			can also express dependencies via method parameters. These dependencies are fulfilled by Dagger 2.
			You can use the
			`@Singleton `
			annotation to indicate that there should be only one
			instance of the object. 
		
	</section>
	<section id="dagger2_overview_wiringup">
		<title>Wiring up the consumer and provider via the @Component annotation 
		
			The
			`@Component`
			is used on an interface.
			Such an interface is used by Dagger 2 to generate code, the base pattern is that is adds the
			`Dagger`
			prefix to the interface name. This generate class has a
			`create`
			method which allows configuring the objects based on the given configuration. The methods defined on the interface
			are available to access the generated objets.
		
		
			A
			`@Component`
			interface defines the connection
			between provider of objects (modules)
			and the objects which expresses a dependency.
		
	</section>

	<section id="dagger2_annotationsummery">
		<title>Summary of annotations and their purpose

		<table frame='all'>
			<title>Annotation summary of Dagger 2
			<tgroup cols='2' align='left' colsep='1' rowsep='1'>
				<colspec colname='c1' colwidth="1*" />
				<colspec colname='c2' colwidth="2*" />
				<thead>
					<row>
						<entry>Annotation</entry>
						<entry>Usage</entry>
					</row>
				</thead>
				<tbody>
					<row>
						<entry>
							`@Module`
						</entry>
						<entry>
							Used on classes which contain
							annotated with
							`@Provides`
							.
						</entry>
					</row>
					<row>
						<entry>
							`@Provides`
						</entry>
						<entry>
							Can be used on methods in classes annotated with
							`@Module`
							and is used for methods which provides objects for dependencies
							injection.
						</entry>
					</row>
					<row>
						<entry>
							`@Singleton`
						</entry>
						<entry>Single instance of this provided object is created and shared.
						</entry>
					</row>
					<row>
						<entry>
							`@Component`
						</entry>
						<entry>Used on an interface. This interface is used by Dagger 2 to generate code which uses the modules to fulfill
							the requested dependencies.
						</entry>
					</row>
				</tbody>
			</tgroup>
		</table>
	</section>

=== Using Dagger 2 with Eclipse and Maven

		To use Eclipse and Maven together with Dagger 2 you can install the Maven tooling and the apt plug-in which
			allows Maven to configure the annotation processors directly. For Eclipse Maven support use the update site of your
			release and afterwards install the m2e-apt tooling via the
			http://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt update site.
		
		After the installation you can turn apt-processing on via the Eclipse preferences.
		
			<mediaobject>
				<imageobject>
					<imagedata fileref="images/mavenaptprocessing.png"/>
				</imageobject>
				<textobject>
					<phrase>Maven apt processing configuration</phrase>
				</textobject>
			</mediaobject>
		
