[[exercise_daggerintro]]
== Exercise: Dependency injection with Dagger 2

=== Create example project for the usage of Dagger 2
		
In this example we will demonstrate the usage of Dagger in a standard Java program managed by Maven.
This exercise can be done via any Java IDE you like, for example the Eclipse IDE with the Maven tooling installed.
Or it can  be developed and compiled via a text editor and the Maven command line. 
If you use Eclipse ensure to install the Maven tooling for it.

Create a new Maven project with the `com.vogella.java.dagger2` top level package.
		
=== Define or adjust Maven build file 
		
Adjust your `pom.xml` to the following.
		
		
			<programlisting language="json">
				<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/maven/pom.xml" />
			</programlisting>
		
[[exercise_daggerintro_classes]]

=== Define classes which have a dependency

Define the following two classes which express dependencies. 
		
			<programlisting language="java">
				<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/maven/User.java" />
			</programlisting>
		

		
			<programlisting language="java">
				<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/maven/BackendService.java" />
			</programlisting>

[[exercise_daggerintro_modules]]
=== Define modules which provides dependencies

Define two class which acts as providers for dependencies.  
		
			<programlisting language="java">

				<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/maven/BackEndServiceModule.java" />
			</programlisting>
		
		
			<programlisting language="java">
				<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/maven/UserModule.java" />
			</programlisting>
		
[[exercise_daggerintro_components]]
=== Define components

Components define from which modules (or other components) dependencies are provided. 
Dagger 2 uses this interface to generate the accessor class which provides the methods defined in the interface.
		
		
			<programlisting language="java">
				<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/maven/MyComponent.java" />
			</programlisting>
[[exercise_daggerintro_uses]]
=== Use the generated dagger code

The usage of the generated code is demonstrated by the following test class.
		
		
			<programlisting language="java">
				<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/maven/Main.java" />
			</programlisting>
		
