[[espresso_introduction]]
== The Espresso test framework
	
_Espresso_ is a testing framework for Android to make it easy to write reliable user interface tests for a single application.
Google released the Espresso_ framework in Oct. 2013. 
Since its 2.0 release Espresso is part of the Android Support Repository.
	
Espresso automatically synchronizes your test actions with the user interface of your application. 
The framework also ensures that your activity is started before the tests run.
It also let the test wait until all observed background activities have finished.
	
	
Espresso has basically three components:

* ViewMatchers - allows to find view in the current view hierarchy
* ViewActions - allows to perform actions on the views
* ViewAssertions - allows to assert state of a view
	
The following code demonstrates the usage of these three elements.
	
	
		<programlisting language="java">
			<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" parse="text" href="./examples/espresso/demo.java" />
		</programlisting>
	
If Espresso does not find a view via the ViewMatchers, it includes the whole view hierarchy into the error message. 
That is useful for analyzing the problem.
	

