[[espresso_exercisesimple]]
== Exercise: A first Espresso test

[[espresso_exercisesimple1]]
=== Create project under test
		
Create a new Android project called _Espresso First_ with the package name _com.vogella.android.espressofirst_. 
Use the _Blank Template_ as basis for this project.
		
Change the generated <filename>activity_main.xml</filename> layout file to the following.
		
[source,xml]
----
include::res/simple/activity_main.xml[]
----
		
Create a new file called <filename>activity_second.xml</filename>.
		
[source,xml]
----
include::res/simple/activity_second.xml[]
----	
		

Create a new activity with the following code.

[source,java]
----
include::res/simple/SecondActivity.java[]
----		
		
Also adjust your `MainActivity` class.
		
[source,java]
----
include::res/simple/MainActivity.java[]
----	
		
[[espresso_exercisesimple2]]
=== Adjust the app build.gradle
		
Add the AndroidJUnitRunner as value for the <parameter>testInstrumentationRunner</parameter> parameter. 
Also add the corresponding entry in the <filename>app/build.gradle</filename> file.

[source,java]
----
include::res/simple/build.gradle[]
----	
		
[[espresso_exercisesimple3]]
=== Create your Espresso test

[source,java]
----
include::res/simple/MainActivityEspressoTest.java[]
----
			
[[espresso_exercisesimple4]]
=== Run your test

		
Ensure that you have selected_Android Instrumentation Tests_ in the_Build Variants_.
Run your tests via your IDE or directly via Gradle. 
See <<espresso_runningespressotests>> for details.
