== Security and permissions

=== Security concept in Android

The Android system installs every Android application with a
unique user and group ID. Each
application file is
private to this
generated user, e.g., other
applications cannot access these files. In
addition, each Android
application is started in its own
process.

Therefore, by means of the underlying Linux kernel,
every Android
application is
isolated from other
running
applications.

If data should be shared, the application must do this
explicitly via an Android component which handles the
sharing of the
data,
e.g.,
via a service
or a content provider.

=== Permission concept in Android

Android contains a permission system and predefined
permissions
for certain tasks. Every application can request
required
permissions
and also define new permissions. For example, an application may
declare
that it
requires access to
the Internet.

Permissions have different levels. Some permissions are
automatically granted by the Android system, some are
automatically
rejected. In most cases the requested permissions are presented
to
the
user before installing the
application. The user needs
to
decide if
these permissions shall be given to the application.

If the user denies a required permission, the related
application cannot be
installed. The check of
the permission
is only
performed during
installation, permissions
cannot be denied or granted
after the
installation.

An Android application declares the required permissions in its
_AndroidManifest.xml_
configuration file. It can also define additional permissions which
it can use to restrict access to certain
components.

NOTE: Not all users pay attention to the required permissions during installation. 
But some users do and they write negative reviews on Google Play if they believe the application is too invasive.

=== Runtime permissions

Android 6.0 Marshmallow (API 23) introduced a new runtime permission model. If your application targets Android 6.0,
you must use the new permissions model. See
https://developer.android.com/preview/features/runtime-permissions.html - Official documentation
for details.

